---
title: "Reporting Regression Results"
author: "Prof. Bell"
format:
  html:
    embed-resources: true
---

Victims of violent crime are 10% less likely to believe that more police will make their neighborhood safer, on average. Respondents who have a positive view of the police are more likely to believe that the police will make their neighborhoods safer compared to those with a poor view of the police, on average.

```{r}
#| label: setup
#| message: false
#| echo: false

library(tidyverse)
library(sjPlot)

dc <- read_csv("31119329.csv")
```

```{r}
#| label: police
#| message: false
#| echo: false

safe <- dc |>
  filter(q21anet != "DK/No opinion" & q20net != "DK/No opinion" & !str_detect(hoodsafe, "VOL") & !str_detect(ratepolice, "VOL")) |>
  mutate(policesafe = ifelse(q21anet == "Would reduce crime NET", 1 ,0),
         ratepolice = factor(ratepolice, levels = c("Poor", "Not so good", "Good", "Excellent")),
         hoodsafe = factor(hoodsafe, levels = c("Not safe at all", "No too safe", "Somewhat safe", "Very safe")),
         q20net = ifelse(q20net == "Not victim of violent crime", 0, 1)) |>
  rename(PoliceRating = ratepolice,
         NeighborhoodSafe = hoodsafe,
         CrimeVictim = q20net)

reg_safe <- lm(policesafe ~ PoliceRating + NeighborhoodSafe + CrimeVictim, weight = weight, data = safe)

tab_model(reg_safe,
          prefix.labels = "label",
          show.reflvl = TRUE,
          show.ci = FALSE,
          dv.labels = "Police will make neighborhood safer")
```