---
title: "Assignment #2"
author: "SMPA 2152 (Prof. Bell)"
# format:
  # pdf:
  #   mainfont: "Arial"
  #   keep-tex: true
  #   include-in-header:
  #      text: |
  #        \usepackage{fvextra}
  #        \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines=true, breakanywhere=true, breaksymbol=, breakanywheresymbolpre=,commandchars=\\\{\}}
  #        \DefineVerbatimEnvironment{OutputCode}{Verbatim}{breaklines=true, breakanywhere=true, breaksymbol=, breakanywheresymbolpre=,commandchars=\\\{\}}
format: gfm
execute:
  echo: true
  include: true
  warning: false
  message: false
editor_options: 
  chunk_output_type: console
---
\vspace{-3em}

For this homework, please use the `assignment2_template.R` script. Please submit your completed `.R` script via Blackboard. In addition, please submit a Word document or PDF containing the visualizations for each question *as well as your written response to the prompt*.

You may complete the assignments on your own or in collaboration with other students. This means that you may work together to write code and/or solve problems. **Do not split up the questions or combine independent work.**

If you work with other students, please indicate their names at the top of your submission. Each student must submit an assignment on Blackboard.
\vspace{-1em}

---

Before you begin, you will need to install and load the `{moderndive}` package (as well as any other packages you will need) and load the `house_prices` data.

1. Do homes with better views command a higher sales price? Please report prices in $1000s, so divide price by 1000. (For `view`, 0 = Poor, 1 = Fair, 2 = Average, 3 = Good, and 4 = Very Good.)

2. Design style has changed over the past century. Use a scatterplot and best fit lines to show how the number of bathrooms compares to the number of bedrooms. Do homes built on or after 1990 tend to have more bathrooms per bedroom than homes built before 1990? (Hint: Recall the result of a logical operator applied to a vector of values. Create a new column that is made up of `TRUE` and `FALSE` values.)

3. Complete the following code to generate a line graph showing how the number of monthly home sales changes over the course of the year (we will learn what this code does in a couple of weeks). Modify the axes to better fit the data. What is the most popular time of year for home sales? Why do you think this might be?