---
title: "Problem Set #3"
author: "SMPA 2152 (Prof. Bell)"
# format:
#   pdf:
#     mainfont: "Arial"
#     keep-tex: true
#     include-in-header:
#        text: |
format: gfm
execute:
  echo: true
  include: true
  warning: false
  message: false
editor_options: 
  chunk_output_type: console
---
\vspace{-3em}

This week's homework uses data on union membership in the United States from [\mbox{UnionStats.com}](https://www.unionstats.com/) by Barry Hirsch (Georgia State University), David Macpherson (Trinity University), and William Even (Miami University). The data is provided to you as `union_membership.csv`.

You will find the following columns in the data:

|variable           |class     |description        |
|:------------------|:---------|:------------------|
|state_census_code  |double    |Census state code used in CPS |
|state              |character |State name |
|employment  |double    |Wage and salary employment in thousands |
|members     |double    |Employed workers who are union members in thousands |
|state_abbreviation |character |State abbreviation |
|year               |double    |Year of the survey |

For this homework, please submit a `.qmd` file as well as a rendered `.html` (with the proper header using `embed-resources: true`) or `.pdf` file. If you are unable to successfully render your `.qmd` script, you should still submit it for partial credit.

You may complete the assignments on your own or in collaboration with other students. This means that you may work together to write code and/or solve problems. **Do not split up the questions or combine independent work.**

If you work with other students, please indicate their names at the top of your submission. Each student must submit an assignment on Blackboard.
\vspace{-1em}

---

1. Load the `union_membership.csv` data.

2. Generate a nicely-formatted table showing the five states with the largest percentage of union members in 2022.

3. Create a nicely-formatted graph that shows the total number of union members in millions of workers over time.

    *Hint: The `members` column is already in thousands.*

4. Make the same graph, but this time, use the *percentage* of workers who are in a union rather than the total number of union members.

5. Produce a nicely-formatted table showing the five states with the largest percentage point change in the percent of workers who are unionized between 1983 and 2022. (A percentage point change means that you are subtracting one percentage from another.)

    *Hint: You will need to use the functions `first()` and `last()` to answer this question. Check the `dplyr` cheat sheet for a clue about where to use these functions.*