---
title: "Problem Set #4"
author: "SMPA 2152 (Prof. Bell)"
# format:
#   pdf:
#     mainfont: "Arial"
#     keep-tex: true
#     include-in-header:
#        text: |
format: gfm
execute:
  echo: true
  include: true
  warning: false
  message: false
editor_options: 
  chunk_output_type: inline
---
\vspace{-3em}

This week's homework uses two data sources:

* data on monthly inflation from the [Federal Reserve Bank of St. Louis](https://fred.stlouisfed.org/series/CPIAUCSL). The data measures the percentage change in prices from the previous year.
* data on President Biden's approval rating from FiveThirtyEight (no longer publicly available).

We will be exploring whether the inflation rate affected President Biden's approval rating.

For this homework, please submit a `.qmd` file as well as a rendered `.html` (with the proper header using `embed-resources: true`) or `.pdf` file. If you are unable to successfully render your `.qmd` script, you should still submit it for partial credit.

You may complete the assignments on your own or in collaboration with other students. This means that you may work together to write code and/or solve problems. **Do not split up the questions or combine independent work.**

If you work with other students, please indicate their names at the top of your submission. Each student must submit an assignment on Blackboard.
\vspace{-1em}

---

1. Load the `inflation.csv` data and turn it into tidy data.

2. Calculate President Biden's average approval rating (`approve_estimate`) in each month and join the `presidential_approval.csv` data to the inflation data.

    *Hint: You may need to convert the month numbers in the inflation data into a numeric vector rather than a character vector.*

3. Make a graph comparing the inflation rate and President Biden's approval rating. Use the color `"springgreen3"` to indicate presidential approval and any other color to indicate the inflation rate. Is presidential approval related to the inflation rate? Why or why not?

    *Hint: You can use the make_date() function to create a date column for your x-axis:*