---
title: "Lab #1 - Data Visualization"
author: "SMPA 2152 (Prof. Bell)"
# format:
#   pdf:
#     mainfont: "Arial"
#     keep-tex: true
#     include-in-header:
#        text: |
#          \usepackage{fvextra}
#          \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines=true, breakanywhere=true, breaksymbol=, breakanywheresymbolpre=,commandchars=\\\{\}}
#          \DefineVerbatimEnvironment{OutputCode}{Verbatim}{breaklines=true, breakanywhere=true, breaksymbol=, breakanywheresymbolpre=,commandchars=\\\{\}}
format: gfm
execute:
  echo: true
  include: true
  warning: false
  message: false
editor_options: 
  chunk_output_type: console
---
\vspace{-3em}

For this lab, we will practice creating data visulization in R using the `ggplot2` package with data on SAT and GPA scores from 1000 students. This data was collected in the 1990s from various universties.

Please use the `lab1_template.R` script. Please submit your completed `.R` script via Blackboard. In addition, please submit a Word document or PDF containing the visualizations and your written responses to each question.

All graphs must be properly labeled with titles, axis labels, and a caption. You must use a `theme` function to improve the appearance of your graphs, but you may choose which theme you prefer.

You may complete the assignments on your own or in collaboration with other students. This means that you may work together to write code and/or solve problems. **Do not split up the questions or combine independent work.**

As a reminder, this course permits virtually unlimited use of AI tools on **code**. However, the use of AI tools for **written text** (e.g., explanations, analysis, etc.) is not permitted.

If you work with other students, please indicate their names at the top of your submission. Each student must submit an assignment on Blackboard.
\vspace{-1em}

---

1. Install the `openintro` package, as well as the `tidyverse` (if necessary). Load the `tidyverse` and `openintro` packages, and then load the `satgpa` data using the `data()` function.

2. Look at the help file for `satgpa`. What is the theoretical maximum value of the `sat_sum` column? Using the `max()` function, what is the actual maximum value in the data? What does this tell you about the students in this dataset? Do you think this data is representative of all the students who took the SAT?

    *Hint: Remember that we can use the `$` to indicate that we want to use a column inside of a particular dataframe, e.g., `data$col`.*

3. Let's learn a little more about how students performed on the two sections of the SAT: the verbal (reading comprehension) section and the math section. Generate two graphs, each one showing the count of students by score for each section. How do these two distributions compare?

4. The data contains a column called `sex` where `"1" == "Male"` and `"2" == "Female"`. Generate a graph comparing the distributions of `sat_sum` for the two sexes. Be sure to change the labels on the axis to use words rather than numbers for the sexes. What do you notice about the two distributions?

    *Hint: You should use the `factor()` function around the `sex` variable inside the `aes()` function. Why do you think this is?*

5. Is a student's SAT score or their high school GPA a better predictor of their first year college GPA? Use two graphs, each comparing one of these measures with first year college GPA, to answer this question.

    *Hint: Each graph will have at least two `geom` laters.*