---
title: "Lab #5 - Text-as-Data"
author: "SMPA 2152 (Prof. Bell)"
# format:
#   pdf:
#     mainfont: "Arial"
#     keep-tex: true
#     include-in-header:
#        text: |
#          \usepackage{fvextra}
#          \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines=true, breakanywhere=true, breaksymbol=, breakanywheresymbolpre=,commandchars=\\\{\}}
#          \DefineVerbatimEnvironment{OutputCode}{Verbatim}{breaklines=true, breakanywhere=true, breaksymbol=, breakanywheresymbolpre=,commandchars=\\\{\}}
format: gfm
execute:
  echo: true
  include: true
  warning: false
  message: false
editor_options: 
  chunk_output_type: console
---
\vspace{-3em}

For this assignment, we will use LDA topic modeling of State of the Union addresses delivered by the President to see how topics differ between Democratic and Republican presidents as well as over time. **For this assignment, you will need to install the `sotu` package.**

Please use the `lab5_template.R` script. Please submit your completed `.R` script via Blackboard. In addition, please submit a Word document or PDF containing the visualizations and your written responses to each question.

All graphs must be properly labeled with titles, axis labels, and a caption. You must use a `theme` function to improve the appearance of your graphs, but you may choose which theme you prefer.

You may complete the assignments on your own or in collaboration with other students. This means that you may work together to write code and/or solve problems. **Do not split up the questions or combine independent work.**

As a reminder, this course permits virtually unlimited use of AI tools on **code**. However, the use of AI tools for **written text** (e.g., explanations, analysis, etc.) is not permitted.

If you work with other students, please indicate their names at the top of your submission. Each student must submit an assignment on Blackboard.
\vspace{-1em}

---

1. The `sotu` package contains two objects (i.e., they are referenced by name without `()` or `data()`): `sotu_meta`, which is a data frame with information on each SOTU address, and `sotu_text`, which is a character vector of SOTU addresses. These line up with the rows in `sotu_meta`. Add a column to `sotu_meta` that contains the text of each SOTU address.

2. We will only use SOTU speeches (not written addresses) since 1934 for this analysis.

3. Use a loop to generate a text file for each year's SOTU address. Use these text files to conduct LDA topic modeling in Voyant Tools (`voyant-tools.org`). In your PDF or Word document, please include a screenshot of the Voyant Tools interface showing the topics generated by LDA topic modeling.


4. Export the topic model results from Voyant Tools as a TSV file. Import this TSV file into R and merge it with `sotu_lim` so that you have the topic proportions for each SOTU address.

To merge the data, use the following code:

```{r}
#| include: TRUE
#| eval: FALSE

df <- inner_join(
  sotu_meta, # This is the original data frame (without the SOTU texts)
  topics,
  by = join_by(year)
)
```

5. Generate a graph showing the average weight of one topic of your choice by party. Provide a brief written analysis of the results. (You should use meaningful topic names in your visualization and analysis.)

6. Generate a graph showing the weight of one topic of your choice by party over time. Provide a brief written analysis of the results.

    *Hint: `geom_smooth()` (without `method = "lm"`) is likely to be a better choice here than `geom_line()`.*