---
title: "Assignment #6"
author: "SMPA 2152 (Prof. Bell)"
# format:
#   pdf:
#     mainfont: "Arial"
#     keep-tex: true
#     include-in-header:
#        text: |
#          \usepackage{fvextra}
#          \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines=true, breakanywhere=true, breaksymbol=, breakanywheresymbolpre=,commandchars=\\\{\}}
#          \DefineVerbatimEnvironment{OutputCode}{Verbatim}{breaklines=true, breakanywhere=true, breaksymbol=, breakanywheresymbolpre=,commandchars=\\\{\}}
format: gfm
execute:
  echo: true
  include: true
  warning: false
  message: false
editor_options: 
  chunk_output_type: inline
---

For this week's homework, we will use hypothesis tests to explore Americans' views of free expression on college campuses. You will need to download the data for the [Ipsos/Knight Foundation Survey: Free Expression in America Post-2020](https://doi.org/10.25940/ROPER-31119146) from Roper iPoll. You will need to dowload the `.csv` file from Roper iPoll and upload it to your Posit Cloud project.

For each question below, you must write both the $H_0$ and the $H_A$. How do you interpret the results of each hypothesis test?

1. Conduct a hypothesis test showing whether a majority of Americans believe that freedom of speech is "extremely important" to them (`Q1_5`).

2. Conduct a hypothesis test showing whether the proportion of college students who believe that colleges and universities should **allow** offensive political speech on campus is less than among non-college students (`Q11_4`).

    Please note that **non**-college students are represented with the values `No` *and* `NA` in the variable `Student1`; any other values represent college students. You should have 4,276 non-college students and 1,023 college students. 
3. Now, we will focus only on college students. Conduct a hypothesis test showing whether a different proportion of self-identified Democratic and Republican (`QPID100`) college students agree that, "The climate at my school or on my campus prevents some people from saying things they believe because others might find it offensive" (`Q16_5`).